name: py36
channels:
  - defaults
  - conda-forge
dependencies:
  - m2r=0.2.1=py_0
  - rdkit=2019.03.4=py36hb31dc5d_0
  - sphinxcontrib-autoprogram=0.1.5=py_1
  - sphinxcontrib-programoutput=0.14=py_0
  - setuptools=41.0.1=py36_0
  - sphinx=2.1.2=py_0
  - sphinx_rtd_theme=0.4.3=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
